# Generated by Django 2.2.4 on 2020-12-15 09:55

import datetime
from django.db import migrations, models
import myapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190904_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionPuntaje',
            fields=[
                ('asigid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userid', models.UUIDField(null=True)),
                ('tareid', models.UUIDField(null=True)),
                ('puntaje', models.IntegerField()),
            ],
            options={
                'db_table': '"v1"."asignaciones_puntajes"',
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('barrioid', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"v1"."barrios"',
            },
        ),
        migrations.CreateModel(
            name='Cartografia',
            fields=[
                ('cartografiaid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrid', models.UUIDField(null=True)),
                ('osmid', models.CharField(max_length=255)),
                ('elemosmid', models.UUIDField(null=True)),
                ('userid', models.UUIDField(null=True)),
                ('estado', models.IntegerField(default=0)),
                ('tareid', models.UUIDField(null=True)),
            ],
            options={
                'db_table': '"v1"."cartografias"',
            },
        ),
        migrations.CreateModel(
            name='Conflictividad',
            fields=[
                ('confid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"v1"."conflictividades"',
            },
        ),
        migrations.CreateModel(
            name='Contexto',
            fields=[
                ('contextoid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': '"v1"."contextos"',
            },
        ),
        migrations.CreateModel(
            name='ContextoProyecto',
            fields=[
                ('contproyid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proyid', models.UUIDField(null=True)),
                ('contextoid', models.UUIDField(null=True)),
            ],
            options={
                'db_table': '"v1"."contextos_proyecto"',
            },
        ),
        migrations.CreateModel(
            name='Contextualizacion',
            fields=[
                ('contxtid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hecho', models.DateField()),
                ('hora_hecho', models.TimeField()),
                ('dia', models.IntegerField()),
                ('confid', models.UUIDField(null=True)),
                ('generoid', models.UUIDField(null=True)),
                ('edad', models.IntegerField()),
                ('nivelid', models.UUIDField(null=True)),
                ('nombre_barrio', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField(null=True)),
                ('barrioid', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '"v1"."contextualizaciones"',
            },
        ),
        migrations.CreateModel(
            name='DelimitacionGeografica',
            fields=[
                ('dimensionid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proyid', models.UUIDField(null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('geojson', models.CharField(max_length=1000, null=True)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': '"v1"."dimensiones_territoriales"',
            },
        ),
        migrations.CreateModel(
            name='ElementoOsm',
            fields=[
                ('elemosmid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('llaveosm', models.CharField(max_length=255)),
                ('valorosm', models.CharField(max_length=255)),
                ('closed_way', models.IntegerField()),
            ],
            options={
                'db_table': '"v1"."elementos_osm"',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('encuestaid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrid', models.UUIDField(null=True)),
                ('koboid', models.UUIDField(null=True)),
                ('contenido', models.CharField(max_length=5000)),
                ('estado', models.IntegerField(default=0)),
                ('observacion', models.CharField(blank=True, max_length=3000, null=True)),
                ('userid', models.UUIDField(null=True)),
                ('tareid', models.UUIDField(null=True)),
            ],
            options={
                'db_table': '"v1"."encuestas"',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('generoid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"v1"."generos"',
            },
        ),
        migrations.CreateModel(
            name='MiembroPlantilla',
            fields=[
                ('miplid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userid', models.UUIDField(null=True)),
                ('estado', models.IntegerField(default=1)),
                ('planid', models.UUIDField(null=True)),
            ],
            options={
                'db_table': '"v1"."miembros_plantilla"',
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('nivelid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"v1"."niveles_educativos"',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('paramid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('paramvalor', models.CharField(max_length=1000)),
                ('paramdesc', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': '"v1"."parametros"',
            },
        ),
        migrations.CreateModel(
            name='PlantillaEquipo',
            fields=[
                ('planid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('userid', models.UUIDField(null=True)),
            ],
            options={
                'db_table': '"v1"."plantillas_equipo"',
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('tiproid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': '"v1"."tipos_proyecto"',
            },
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', myapp.models.MyUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='datoscontexto',
            old_name='proyid',
            new_name='contextoid',
        ),
        migrations.AddField(
            model_name='datoscontexto',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datoscontexto',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datoscontexto',
            name='geojson',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='datoscontexto',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='geojson',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proyfechainicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proypropietario',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tiproid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='dimensionid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='geojson_subconjunto',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='taredescripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tareestado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarefechacreacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 15, 4, 55, 37, 407225), null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tareprioridad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='barrioid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='generoid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horaubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivel_educativo_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puntaje',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accion',
            name='accionid',
            field=models.UUIDField(default=uuid.UUID('e1b07812-7df6-4637-a2bd-130d55d4d040'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datoscontexto',
            name='datatipe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datoscontexto',
            name='datavalor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datoscontexto',
            name='hdxtag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='userid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='decisionproyecto',
            name='desiid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='decisionproyecto',
            name='proyid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='miembroestado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='proyid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='userid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='funcionrol',
            name='accionid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='funcionrol',
            name='rolid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proydescripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proyfechacierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proyfechacreacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='instrid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarerestriccant',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='taretipo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rolid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userestado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userfullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userleveltype',
            field=models.IntegerField(null=True),
        ),
    ]
