# Generated by Django 2.2.4 on 2020-12-15 10:09

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201215_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='accionid',
            field=models.UUIDField(default=uuid.UUID('1ad6f569-e9d6-4616-ac27-339bff9777af'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarefechacreacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 15, 5, 9, 33, 800799), null=True),
        ),
    ]
